# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

project_name: horusec-operator
builds:
  - id: horusec-operator
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./cmd/app
    ldflags:
      - -X github.com/nathanmartinszup/horusec-operator/api/v2alpha1.LatestVersion=v{{ .Version }}
      - -X github.com/nathanmartinszup/horusec-operator/api/v2alpha1.Commit={{ .Commit }}
      - -X github.com/nathanmartinszup/horusec-operator/api/v2alpha1.Date={{ .Date }}
    goos:
      - linux
    goarch:
      - amd64
    binary: horusec-operator
changelog:
  skip: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
archives:
  - format: binary
release:
  draft: true
  extra_files:
    - glob: ./deployments/cosign.pub
signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PWD }}'
    args: ["sign-blob", "-key={{ .Env.COSIGN_KEY_LOCATION }}", "-output=${signature}", "${artifact}"]
    artifacts: all
