# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ReleaseAlpha

on:
  push:
    branches:
      - main
      - release/v2.3

permissions: read-all
jobs:
  ReleaseAlpha:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    env:
      COSIGN_KEY_LOCATION: "/tmp/cosign.key"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Mage
        run: go install github.com/magefile/mage@v1.11

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cosign Installer
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.2.0'

      - name: Install cosign private key
        run: mage WriteCosignKeyToFile
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}

      - name: Set Version to build
        run: mage UpdateVersioningFilesAlpha

      # The changes made in the last step are committed to the branch that the workflow was triggered, this commit is not
      # going to trigger any workflow cause the skip ci in the commit message.
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.4.0
        with:
          push: false
          signoff: true
          author_name: horusec
          author_email: horusec@zup.com.br
          committer_name: horusec
          committer_email: horusec@zup.com.br
          message: "versioning:release - [skip ci] automatic commit updating versioning files"

      #      - name: Build and push
      #        uses: docker/build-push-action@v2
      #        with:
      #          push: true
      #          context: .
      #          file: ./deployments/dockerfiles/Dockerfile
      #          tags: horuszup/horusec-operator:alpha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./deployments/dockerfiles/Dockerfile
          tags: nathanmartins18/testrepository:alpha

      - name: Sign image
        run: mage SingAlphaImage
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PWD }}

      - name: Delete outdate release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: alpha

      - name: Create tag
        id: test
        run: mage CreateAlphaTagTest

      - name: Update alpha release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: alpha
          name: alpha
          draft: false
          prerelease: true
          commitish: ${{ steps.test.outputs.alphaCommitSha }}
          gzip: true
          allow_override: true
          files: |
            cosign.pub:./deployments/cosign.pub
          body: |
            ## Docker images
            - `docker pull horuszup/horusec-operator:alpha`
